config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: { registrations: "registrations", sessions: "sessions" }
  root to: "pages#index"

  resources :members, only: [:index, :show] do
    resources :profiles
  end

  resources :locations do
    get :add_images, on: :member
  end
end

app/models/address.rb
class Address < ApplicationRecord

  validates :line_1, presence: true, length: { minimum: 5, maximum: 30 }
  validates :line_2, allow_blank: true, length: { minimum: 5, maximum: 40 }
  validates :city, presence: true, length: { minimum: 5, maximum: 20 }
  validates :postcode, presence: true, length: { minimum: 6, maximum: 8 }

  validates_numericality_of :latitude, :allow_nil => true
  validates_numericality_of :longitude, :allow_nil => true

  belongs_to :location

  geocoded_by :full_address
  after_validation :geocode, if: ->(obj){ obj.line_1.present? and obj.address_changed? }

  def address_changed?
    line_1_changed? || line_2_changed? || city_changed? || postcode_changed?
  end

  private

  def full_address
    [line_1, line_2, city, postcode].compact.join(", ")
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feature.rb
class Feature < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false },
                    length: { minimum: 1, maximum: 30 }

  has_and_belongs_to_many :locations, join_table: "locations_features"
end

app/models/image.rb
class Image < ApplicationRecord
  validates :caption, length: { minimum: 5, maximum: 50 }, allow_nil: true
  validates :location_id, presence: true

  has_attached_file :image_pic,
    styles: { thumb: "100x100#" },
    default_url: "/images/:style/missing.png",
    :bucket => ENV['S3_BUCKET_NAME'],
    :url => ":s3_domain_url",
    :path => "locations/image_pic/:id/:style/:filename"
    validates_attachment_content_type :image_pic, content_type: /\Aimage\/.*\z/

  belongs_to :location
end

app/models/location.rb
class Location < ApplicationRecord

  validates :name, presence: true, length: { minimum: 5, maximum: 30 }
  validates :point_of_contact, presence: true, length: { minimum: 3, maximum: 20 }
  validates :contact_number, presence: true, length: { minimum: 10, maximum: 20 }
  validates :max_occupancy, presence: true
  validates :price, presence: true
  validates :description, presence: true, length: { minimum: 10, maximum: 250 }

  has_one :address
  has_many :images
  has_and_belongs_to_many :features, join_table: "locations_features"

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :images
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true
  validates :password, presence: true

  has_one :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
  before_save :standardize_name

  validates :first_name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :last_name, presence: true, length: { minimum: 3, maximum: 30 }
  validates :contact_number, presence: true, length: { minimum: 10, maximum: 20 }
  validates :member_id, presence: true

  has_attached_file :profile_pic,
    styles: { thumb: "100x100#" },
    default_url: "/images/:style/missing.png",
    :bucket => ENV['S3_BUCKET_NAME'],
    :url => ":s3_domain_url",
    :path => "profiles/profile_pic/:id/:style/:filename"
    validates_attachment_content_type :profile_pic, content_type: /\Aimage\/.*\z/

  belongs_to :member

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def standardize_name
    first_name.capitalize!
    last_name.capitalize!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:add_images, :show, :update]

  def new
    @location = Location.new
    @location.build_address
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      flash[:success] = "Location Created"
      redirect_to add_images_location_path(@location)
    else
      flash[:danger] = "Location could not be created. See below errors."
      render :new
    end
  end

  def show
    @coordinates = {lng: @location.address.longitude, lat: @location.address.latitude}
    if @location.images == []
      logger.info("====This location does not have any images====")
      @default_url = ActionController::Base.helpers.asset_path('missing_location.png')
    end
  end

  def update
    if @location.update(location_params)
      flash[:success] = "Images Uploaded"
      redirect_to @location
    else

    end
  end

  def add_images
  end

  private

  def set_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:name, :point_of_contact, :contact_number,
                                      :max_occupancy, :size, :price, :description,
                                      address_attributes: [:line_1, :line_2, :city,
                                                            :postcode],
                                      images_attributes: [:image_pic, :caption, :location_id],
                                      feature_ids: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit]
  before_action :require_same_member, only: [:show, :edit]

  def index
  end

  def show
    @member = current_member
  end

  def new
    @profile = current_member.build_profile
  end

  def edit
  end

  def create
    @profile = current_member.create_profile(profile_params)
    if @profile.save
      flash[:success] = "Your profile was successfully created"
      redirect_to root_path
    else
      flash.now[:danger] = "Something went wrong"
      render :new
    end
  end

  def update
    @profile = current_member.profile
    if @profile.update(profile_params)
      flash[:success] = "Your profile was successfully updated"
      redirect_to member_profile_path(@profile)
    else
      flash.now[:danger] = "Something went wrong"
      render :edit
    end
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :contact_number, :member_id, :profile_pic)
  end

  def require_same_member
    if current_member != @profile.member
      flash[:alert] = "Oops. You're not allowed to view that page."
      redirect_to root_path
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def after_sign_up_path_for(resource)
    new_member_profile_path(current_member)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    if resource.profile
      root_path
    else
      flash[:danger] = "You dont have a profile, please complete your profile to access the rest of the site."
      new_member_profile_path(current_member)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a yref="#" class="close" data-dismiss="alert">&#215;</a>
        <% if name == "danger" %>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <% end %>
        <p>
          <%= msg %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Spaces", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Create Location", new_location_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !member_signed_in? %>
          <li><%= link_to "Sign in", new_member_session_path %></li>
          <li><%= link_to "Sign up", new_member_registration_path %></li>
        <% else %>
          <% if !current_member.profile.new_record? %>
            <li><%= link_to "View Profile", member_profile_path(current_member, current_member.profile) %></li>
          <% end %>
          <li><%= link_to "Logout", destroy_member_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spaces</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "http://maps.google.com/maps/api/js?key=#{ENV["GOOGLE_MAPS_KEY"]}" %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <!-- <p class="notice"><%= notice %></p> -->
    <!-- <p class="alert"><%= alert %></p> -->
    <%= render "layouts/messages" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/locations/_form.html.erb
<%= render "shared/errors", obj: @location %>
<%= form_for(@location, html: { multipart: true }) do |f| %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :name, "Name:" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :point_of_contact, "Point of Contact:" %>
        <%= f.text_field :point_of_contact, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :contact_number, "Contact Number:" %>
        <%= f.text_field :contact_number, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= f.fields_for :address do |a| %>
      <div class="form-group">
        <%= a.label :line_1, "Line 1:" %>
        <%= a.text_field :line_1, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= a.label :line_2, "Line 2:" %>
        <%= a.text_field :line_2, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= a.label :city, "City:" %>
        <%= a.text_field :city, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= a.label :postcode, "Postcode:" %>
        <%= a.text_field :postcode, class: "form-control" %>
      </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :max_occupancy, "Max Occupancy:" %>
        <%= f.text_field :max_occupancy, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :size, "Size:" %>
        <%= f.text_field :size, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="form-group">
        <%= f.label :price, "Price:" %>
        <%= f.text_field :price, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :features_ids, "Features:" %>
        <%= f.select :feature_ids, Feature.all.pluck(:name, :id), {:include_hidden => false}, { multiple: true, class: "selectize" } %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <div class="form-group">
        <%= f.label :description, "Description:" %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <%= f.submit "Create", class: "btn btn-primary btn-block" %>
    </div>
  </div>
<% end %>

app/views/locations/add_images.html.erb
<%= render "shared/page_title", title: "Upload Images" %>
<div class="col-md-8 col-md-offset-2">
	<div class="">
		<h5>Upload images to show off your location</h5>
		<%= link_to "Skip", @location, class: "btn" %>
	</div>
	<%= form_for @location, html: { multipart: true, class: "dropzone"}  do |f| %>
			<%= f.fields_for :images, Image.new do |image| %>
				<div class="fallback">
		      <%= image.file_field :image_pic %>
		      <%= f.submit "Add Image" %>
		   	</div>
			<% end %>
	<% end %>
	<div class="">
		<%= link_to "Save and Continue", @location, class: "btn btn-primary" %>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function(){
	// disable auto discover
	Dropzone.autoDiscover = false;

	var dropzone = new Dropzone (".dropzone", {
		maxFilesize: 2,
		paramName: "location[images_attributes][0][image_pic]", // Rails expects the file upload to be something like model[field_name]
		addRemoveLinks: false
	});
});
</script>

app/views/locations/new.html.erb
<%= render "shared/page_title", title: "Create a Location" %>
<%= render "form" %>

app/views/locations/show.html.erb
<div class="row">
  <div class="col-md-3">
    <% if !@default_url %>
      <img src="<%= @location.images.first.image_pic.url %>" alt="" width="100%">
    <% else %>
      <img src="<%= @default_url %>" alt="" width="100%">
    <% end %>
  </div>
  <div class="col-md-9">
    <h3><%= @location.name %></h3>
    <hr>
    <div class="row">
      <div class="col-md-8">
        <p>
          <h4>About:</h4>
          <%= @location.description %>
        </p>
        <div class="">
          <ul>
            <% @location.features.each do |f| %>
              <li><%= f.name %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="col-md-4">
        <h4>Information:</h4>
        <p>
          Max Occupancy: <%= @location.max_occupancy %><br>
          Size: <%= @location.size %><br>
          Price: <%= number_to_currency(@location.price, unit: "£") %>
        </p>
        <p>
          <h5>Point of Contact:</h5>
          <%= @location.point_of_contact %><br>
          Tel: <%= @location.contact_number %>
        </p>
        <p>
          <h5>Address:</h5>
          <%= @location.address.line_1 %><br>
          <% if @location.address.line_2 %>
            <%= @location.address.line_2 %><br>
          <% end %>
          <%= @location.address.city %><br>
          <%= @location.address.postcode %>
        </p>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div id="map" class="col-md-3" style="height: 400px;"></div>
</div>

<script type="text/javascript">
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
	  markers = handler.addMarker(<%=raw @coordinates.to_json %>);
	  handler.bounds.extendWith(markers);
	  handler.fitMapToBounds(markers);
	  handler.getMap().setZoom(15);
	});
</script>

app/views/pages/index.html.erb
<div class="jumbotron text-center">
  <h1>Welcome to Spaces</h1>
  <hr>
  <p>Find the perfect place to host your next meeting</p>
  <%= link_to "Become a member", new_member_registration_path, class: "btn btn-lg btn-primary" %>
  <div class="image-container">
    <%= image_tag("office-1.jpg", size: "300", class: "img-thumbnail") %>
    <%= image_tag("office-6.jpg", size: "300", class: "img-thumbnail") %>
    <%= image_tag("office-4.jpg", size: "300", class: "img-thumbnail") %>
  </div>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: path, html: { multipart: true } do |f| %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="form-group">
      <%= f.label :first_name, "First Name:" %>
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :last_name, "Last Name:" %>
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :contact_number, "Contact Number:" %>
      <%= f.text_field :contact_number, class: "form-control" %>
    </div>
    <div class="form-group">
      <% if params[:action] == "edit" %>
        <p>Change your profile picture</p>
      <% else %>
        <p>Upload a profile picture</p>
      <% end %>
      <%= f.file_field :profile_pic %>
    </div>
    <div class="">
      <%= f.submit "Save", class: "btn btn-primary" %>
    </div>
  </div>
</div>
<% end %>

app/views/profiles/edit.html.erb
<%= render "shared/page_title", title: "Edit your profile" %>
<%= render "form", path: member_profile_path %>

app/views/profiles/new.html.erb
<%= render "shared/page_title", title: "Complete your profile" %>
<%= render "form", path: member_profiles_path %>

app/views/profiles/show.html.erb
<%= render "shared/page_title", title: "Your Profile" %>
<div class="row">
  <div class="col-md-3">
    <img src="<%= @profile.profile_pic.url %>" alt="" width="225px">
  </div>
  <div class="col-md-6">
    <h3>Hi <%= @profile.first_name %>,</h3>
    <p>Here you will find the information we hold on you, and soon, the details of your bookings!</p>
    <div class="seperator">
      <p><strong>Full Name:</strong> <%= @profile.full_name %></p>
      <p><strong>Contact Number:</strong> <%= @profile.contact_number %></p>
      <p><strong>Email:</strong> <%= @member.email %></p>
      <%= link_to "Edit Profile", edit_member_profile_path(current_member, current_member.profile), :class => "btn btn-warning btn-xs" %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %> prohibited this <%= obj.class %> from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1><%= title %></h1>
  </div>
</div>
<hr>